import { Link, useOutletContext } from "react-router-dom"

export default function ShoppingList() {
    const {
        shoppingList,
        removeFromShoppingList,
        clearShoppingList
    } = useOutletContext()

    // Format shopping list for sharing
    const formatShoppingList = () => {
        const header = `Shopping List - ${shoppingList.length} items\n\n`
        const items = shoppingList.map(item => 
            `☐ ${item.ingredient} (for ${item.recipeTitle})`
        ).join('\n')
        const footer = `\n\nTip: Copy this list to your phone's notes app for checkable boxes!\n\nGenerated by Recipe Optimizer App`
        
        return header + items + footer
    }

    // Share via email - opens in new tab
    const handleEmailList = () => {
        const emailBody = formatShoppingList()
        const subject = `Shopping List - ${shoppingList.length} items`
        const mailtoLink = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(emailBody)}`
        window.open(mailtoLink, '_blank')
    }

    // Share via Web Share API (mobile) or copy to clipboard
    const handleShareList = async () => {
        const shareData = {
            title: `Shopping List - ${shoppingList.length} items`,
            text: formatShoppingList()
        }

        if (navigator.share) {
            // Mobile/supported browsers - native share
            try {
                await navigator.share(shareData)
            } catch (error) {
                console.log('Share cancelled or failed')
            }
        } else {
            // Fallback - copy to clipboard
            try {
                await navigator.clipboard.writeText(formatShoppingList())
                alert('Shopping list copied to clipboard!')
            } catch (error) {
                // Final fallback - show text in popup
                prompt('Copy this shopping list:', formatShoppingList())
            }
        }
    }

    return (
        <div className="shopping-list-page">
            <header>
                <h1>Shopping List</h1>
            </header>
            {shoppingList.length > 0 ? (
                <>
                    <ul className="ingredient-list-container">
                        {shoppingList.map(item => (
                            <p key={item.id} className="ingredient">
                                <span>&bull; {item.ingredient} (for {item.recipeTitle})</span>
                                <span onClick={() => removeFromShoppingList(item.id)}>remove</span>
                            </p>
                        ))}
                    </ul>
                    
                    <div className="shopping-list-actions">
                        <button onClick={handleEmailList}>📧 Email List</button>
                        <button onClick={handleShareList}>📱 Share List</button>
                        <button onClick={clearShoppingList}>🗑️ Clear All</button>
                    </div>
                </>
            ) : (
                <div className="no-shopping-items">
                    <h2>Your shopping list is empty!</h2>
                    <p>Add missing ingredients from recipes to build your shopping list.</p>
                    <Link to="/">Find Recipes</Link>
                </div>
            )}
        </div>
    )
}